workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      java: 17
      flutter: stable
    scripts:
      # - name: Flutter Doctor
      #   script: flutter doctor
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Flutter Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - subfolder_name/build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    triggering: 
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    publishing:
      email:
        recipients:
          - pcomar.lenovo@gmail.com
        notify:
          success: true
          failure: false