workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      java: 17
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Fetch Outdated Packages
        script: | 
          flutter pub outdated
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    triggering: 
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
    publishing:
      email:
        recipients:
          - pcomar.lenovo@gmail.com
        notify:
          success: true
          failure: false