// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9Pjn4pgD-jARw6xj1-w0AQ2MOj--rM0',
    appId: '1:994030083317:web:fdbef5110b0dc370b1f9bc',
    messagingSenderId: '994030083317',
    projectId: 'innotes-96c72',
    authDomain: 'innotes-96c72.firebaseapp.com',
    storageBucket: 'innotes-96c72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOzXpMRcYwcO2e8Eq_UDqxrPanWYcskQ',
    appId: '1:994030083317:android:43ce8dc20503abb7b1f9bc',
    messagingSenderId: '994030083317',
    projectId: 'innotes-96c72',
    storageBucket: 'innotes-96c72.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh9Pjn4pgD-jARw6xj1-w0AQ2MOj--rM0',
    appId: '1:994030083317:web:f8886d9eb268698fb1f9bc',
    messagingSenderId: '994030083317',
    projectId: 'innotes-96c72',
    authDomain: 'innotes-96c72.firebaseapp.com',
    storageBucket: 'innotes-96c72.appspot.com',
  );
}
